spring.application.name=user-service

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.url=jdbc:postgresql://localhost:5432/progressor
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false

jwt.secret = ${JWT_SECRET}
jwt.access-token.expiration = 900000
jwt.refresh-token.expiration = 604800000