spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://localhost:5432/progressor
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false

jwt.secret = 2XFo0sto5Jd4sh6oe9ae65Jg6eoJwy4ef34FUN38ywHGJs778tw
jwt.expiration = 360000
